# Generated by Django 5.1.5 on 2025-01-25 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeAttributeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('created_by', models.CharField(choices=[('SYSTEM', 'System'), ('COMMUNITY', 'Community')], default='SYSTEM', max_length=30)),
                ('relation_type', models.CharField(choices=[('INGREDIENT', 'Ingredient'), ('KEYWORD', 'Keyword'), ('CUISINE', 'Cuisine'), ('DIETARY', 'Dietary')], max_length=30)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_created_attributes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
                'unique_together': {('value', 'relation_type')},
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('instructions', models.TextField(max_length=2000)),
                ('difficulty', models.CharField(choices=[('SUPER_EASY', 'Super Easy'), ('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard'), ('SUPER_HARD', 'Super Hard')], default='MEDIUM', max_length=100)),
                ('time', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL)),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_cuisine', to='recipe.recipeattributetype')),
                ('dietary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_dietary', to='recipe.recipeattributetype')),
                ('ingredients', models.ManyToManyField(related_name='recipe_ingredients', to='recipe.recipeattributetype')),
                ('keywords', models.ManyToManyField(related_name='recipe_keywords', to='recipe.recipeattributetype')),
            ],
            options={
                'ordering': ('-id',),
                'unique_together': {('title', 'author')},
            },
        ),
    ]
