# Generated by Django 4.0.2 on 2022-02-16 05:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='pub_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
