# Generated by Django 3.2.9 on 2022-02-20 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_course_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='total_enrollment',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
