# Generated by Django 3.2.9 on 2021-11-19 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20211119_0347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('PEPPERONI', 'PEPPERONI'), ('MOZZARELLA', 'MOZZARELLA'), ('BACON', 'BACON'), ('ONION', 'ONION'), ('CAPSICUM', 'CAPSICUM'), ('MUSHROOM', 'MUSHROOM'), ('OLIVES', 'OLIVES')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('PEPPERONI', 'PEPPERONI'), ('SUPREME', 'SUPREME'), ('HAWAIIAN', 'HAWAIIAN'), ('MARGHERITA', 'MARGHERITA'), ('CHEESE', 'CHEESE')], max_length=100)),
                ('toppings', models.ManyToManyField(related_name='pizzas', to='polls.Topping')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.manufacturer')),
            ],
        ),
    ]
